export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";

export const FETCH_ALL_BUSES= "FETCH_ALL_BUSES";
export const FETCH_ALL_USERS= "FETCH_ALL_USERS";
export const ASSIGN_DRIVER_BUSES= "ASSIGN_DRIVER_BUSES";
export const FETCH_ASSIGN_ERROR='FETCH_ASSIGN_ERROR';
export const FETCH_ASSIGN_ClEAN='FETCH_ASSIGN_ClEAN';
// UpdateProfile 
export const FETCH_USER='FETCH_USER';
export const UPDATE_USER='UPDATE_USER';
export const FETCH_USER_REQUEST='FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS='FETCH_USER_SUCCESS'; 
export const FETCH_USER_FAILED='FETCH_USER_FAILED'; 
export const PATCH_USER_SUCCESS='PATCH_USER_SUCCESS';

export const ROUTE_LIST_REQUEST = "ROUTE_LIST_REQUEST";
export const ROUTE_LIST_SUCCESS = "ROUTE_LIST_SUCCESS";
export const ROUTE_LIST_FAIL = "ROUTE_LIST_FAIL";

export const ROUTE_DETAILS_REQUEST = "ROUTE_DETAILS_REQUEST";
export const ROUTE_DETAILS_SUCCESS = "ROUTE_DETAILS_SUCCESS";
export const ROUTE_DETAILS_FAIL = "ROUTE_DETAILS_FAIL";

export const ROUTE_SAVE_REQUEST = "ROUTE_SAVE_REQUEST";
export const ROUTE_SAVE_SUCCESS = "ROUTE_SAVE_SUCCESS";
export const ROUTE_SAVE_FAIL = "ROUTE_SAVE_FAIL";

export const ROUTE_UPDATE_REQUEST = "ROUTE_UPDATE_REQUEST";
export const ROUTE_UPDATE_SUCCESS = "ROUTE_UPDATE_SUCCESS";
export const ROUTE_UPDATE_FAIL = "ROUTE_UPDATE_FAIL";

export const ROUTE_DELETE_REQUEST = "ROUTE_DELETE_REQUEST";
export const ROUTE_DELETE_SUCCESS = "ROUTE_DELETE_SUCCESS";
export const ROUTE_DELETE_FAIL = "ROUTE_DELETE_FAIL";
