export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";
export const FETCH_ALL_BUSES  = "DECREMENT";
export const FETCH_UNASSIGN_ERROR ="FETCH_UNASSIGN_ERROR"
export const UN_ASSIGN_DRIVER_BUSES="UN_ASSIGN_DRIVER_BUSES";
export const FETCH_ALL_ASSIGN_BUSES = "FETCH_ALL_ASSIGN_BUSES";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const ASSIGN_DRIVER_BUSES = "ASSIGN_DRIVER_BUSES";
export const FETCH_ASSIGN_ERROR = "FETCH_ASSIGN_ERROR";
export const FETCH_ASSIGN_ClEAN = "FETCH_ASSIGN_ClEAN";
// UpdateProfile
export const FETCH_USER = "FETCH_USER";
export const UPDATE_USER = "UPDATE_USER";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
export const PATCH_USER_SUCCESS = "PATCH_USER_SUCCESS";

export const ROUTE_LIST_REQUEST = "ROUTE_LIST_REQUEST";
export const ROUTE_LIST_SUCCESS = "ROUTE_LIST_SUCCESS";
export const ROUTE_LIST_FAIL = "ROUTE_LIST_FAIL";
export const DELETE_BUS = "DELETE_BUS";
export const CREATE_BUS = "CREATE_BUS";
export const GET_BUS_BY_ID = "GET_BUS_BY_ID";
export const UPDATE_BUS = "UPDATE_BUS";

export const ROUTE_DETAILS_REQUEST = "ROUTE_DETAILS_REQUEST";
export const ROUTE_DETAILS_SUCCESS = "ROUTE_DETAILS_SUCCESS";
export const ROUTE_DETAILS_FAIL = "ROUTE_DETAILS_FAIL";

export const ROUTE_SAVE_REQUEST = "ROUTE_SAVE_REQUEST";
export const ROUTE_SAVE_SUCCESS = "ROUTE_SAVE_SUCCESS";
export const ROUTE_SAVE_FAIL = "ROUTE_SAVE_FAIL";

export const ROUTE_UPDATE_REQUEST = "ROUTE_UPDATE_REQUEST";
export const ROUTE_UPDATE_SUCCESS = "ROUTE_UPDATE_SUCCESS";
export const ROUTE_UPDATE_FAIL = "ROUTE_UPDATE_FAIL";

export const ROUTE_DELETE_REQUEST = "ROUTE_DELETE_REQUEST";
export const ROUTE_DELETE_SUCCESS = "ROUTE_DELETE_SUCCESS";
export const ROUTE_DELETE_FAIL = "ROUTE_DELETE_FAIL";

/*============ROLE ACTIONS TYPES===============*/
export const CREATE__ROLE__START = "CREATE_ROLE_START";
export const CREATE__ROLE__SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE__ROLE__FAILURE = "CREATE_ROLE_FAILURE";

export const UPDATE__ROLE__START = "UPDATE__ROLE_START";
export const UPDATE__ROLE__SUCCESS = "UPDATE__ROLE_SUCCESS";
export const UPDATE__ROLE__FAILURE = "UPDATE__ROLE__FAILURE";

export const DELETE__ROLE__START = "DELETE__ROLE__START";
export const DELETE__ROLE__SUCCESS = "DELETE__ROLE__SUCCESS";
export const DELETE__ROLE__FAILURE = "DELETE__ROLE__FAILURE";

export const FETCH__ROLES__START = "FETCH__ROLES__START";
export const FETCH__ROLES__SUCCESS = "FETCH__ROLES__SUCCESS";
export const FETCH__ROLES__FAILURE = "FETCH__ROLES__FAILURE";

export const GET__SINGLE__ROLE__START = "GET__SINGLE__ROLE__START";
export const GET__SINGLE__ROLE__SUCCESS = "GET__SINGLE__ROLE__SUCCESS";
export const GET__SINGLE__ROLE__FAILURE = "GET__SINGLE__ROLE__FAILURE";

/*===========ENDO OF ROLE ACTIONTYPES=============*/

/***** ASSIGN BUS TO ROUTE  ***** */

export const ASSIGN__BUS__TO__ROUTE__START = "ASSIGN__BUS__TO__ROUTE__START";
export const ASSIGN__BUS__TO__ROUTE__SUCCESS =
  "ASSIGN__BUS__TO__ROUTE__SUCCESS";
export const ASSIGN__BUS__TO__ROUTE__FAILURE =
  "ASSIGN__BUS__TO__ROUTE__FAILURE";
/***** ASSIGN BUS TO ROUTE END ***** */

/***** UN ASSIGN BUS TO ROUTE  ***** */

export const UNASSIGN__BUS__TO__ROUTE__START =
  "UNASSIGN__BUS__TO__ROUTE__START";
export const UNASSIGN__BUS__TO__ROUTE__SUCCESS =
  "UNASSIGN__BUS__TO__ROUTE__SUCCESS";
export const UNASSIGN__BUS__TO__ROUTE__FAILURE =
  "UNASSIGN__BUS__TO__ROUTE__FAILURE";

/***** UN ASSIGN BUS TO ROUTE END ***** */

/***** FETCH ALL BUS ASSIGMNENT  ***** */

export const FETCH__ALLBUS__ASSIGNMENT__START =
  "FETCH__ALLBUS__ASSIGNMENT__START";
export const FETCH__ALLBUS__ASSIGNMENT__SUCCESS =
  "FETCH__ALLBUS__ASSIGNMENT__SUCCESS";
export const FETCH__ALLBUS__ASSIGNMENT__FAILURE =
  "FETCH__ALLBUS__ASSIGNMENT__FAILURE";

/***** FETCH ALL BUS ASSIGMNENT END ***** */
export const FETCH__ROUTES__START = "FETCH__ROUTES__START";
export const FETCH__ROUTES__SUCCESS = "FETCH__ROUTES__SUCCESS";
export const FETCH__ROUTES__FAILURE = "FETCH__ROUTES__FAILURE";
