export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";

export const FETCH_ALL_BUSES= "FETCH_ALL_BUSES";
export const FETCH_ALL_USERS= "FETCH_ALL_USERS";
export const ASSIGN_DRIVER_BUSES= "ASSIGN_DRIVER_BUSES";
export const FETCH_ASSIGN_ERROR='FETCH_ASSIGN_ERROR';
export const FETCH_ASSIGN_ClEAN='FETCH_ASSIGN_ClEAN';




